### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by oklaova** [likeabbas/cse134b-hw3#1]
Hi github user,
I want to clone this repository. But it contains some fonts, particularly the Operator Mono font in the font folder. I know this font is not free. Do you own them and are you giving permission to clone this repo, and use this font? They will only be used on my personal computer for coding personal project or client works.
They are expensive at this time for me to purchase them.

Thank You.

**Comment by likeabbas** [comment]
Hello @oklavo, 

This repo contains our work for a UCSD web development class. I bought the Operator Mono font a while ago and used it in the project since we had no intention of monetizing the application. This repo used to be private, but I forgot to take out the font before making it public. If you would like to make a PR that removes the font I would merge it. I’m travelling and cannot make those changes myself right now, and I do not recommend using the font in this repo!

**Comment by def14nt** [comment]
@likeabbas Thanks for the font, fam!

**Comment by oklaova** [comment]
what...I can use the fonts now? :) I have not used them. I do my best to respect people works, so I havent used the fonts because you recommended me not to. I will be glad to use them though if you allow me to.
Thanks

**Comment by def14nt** [comment]
Do what you want

**Comment by def14nt** [comment]
It's on github

**Comment by def14nt** [comment]
@oklaova it's a £100 font why not take it

**Comment by def14nt** [comment]
@oklaova it's not rude to use it. It if was he would've taken it down by now
